-- +goose Up

CREATE TABLE subjects (
    id uuid PRIMARY KEY,
    slug varchar(200) NOT NULL UNIQUE,
    display_name varchar(300) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    archived_at timestamptz
);

CREATE TABLE artifact_types (
    id uuid PRIMARY KEY,
    name varchar(300) NOT NULL,
    schema_version varchar(100) NOT NULL,
    domain varchar(100) NOT NULL,
    CONSTRAINT uq_artifact_type_schema UNIQUE (name, schema_version)
);

CREATE TABLE artifacts (
    id uuid PRIMARY KEY,
    artifact_type_id uuid NOT NULL REFERENCES artifact_types(id) ON DELETE RESTRICT,
    semantic_sha256 char(64) NOT NULL,
    content_sha256 char(64) NOT NULL,
    storage_key text NOT NULL,
    size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
    producer_contract varchar(300) NOT NULL,
    implementation_sha256 char(64) NOT NULL,
    policy_sha256 char(64) NOT NULL,
    semantic_parameters jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    verified_at timestamptz NOT NULL,
    CONSTRAINT uq_artifact_semantic_identity UNIQUE (artifact_type_id, semantic_sha256),
    CONSTRAINT uq_artifact_content_storage UNIQUE (content_sha256, storage_key)
);

CREATE TABLE artifact_inputs (
    artifact_id uuid NOT NULL REFERENCES artifacts(id) ON DELETE RESTRICT,
    input_role varchar(200) NOT NULL,
    ordinal integer NOT NULL CHECK (ordinal >= 0),
    input_artifact_id uuid NOT NULL REFERENCES artifacts(id) ON DELETE RESTRICT,
    PRIMARY KEY (artifact_id, input_role, ordinal)
);

CREATE TABLE engine_releases (
    id uuid PRIMARY KEY,
    name varchar(300) NOT NULL,
    release_sha256 char(64) NOT NULL UNIQUE,
    purpose varchar(20) NOT NULL CHECK (purpose IN ('PRODUCT','RESEARCH')),
    created_by varchar(300) NOT NULL,
    sealed_at timestamptz NOT NULL
);

CREATE TABLE engine_release_stages (
    release_id uuid NOT NULL REFERENCES engine_releases(id) ON DELETE RESTRICT,
    stage_id varchar(100) NOT NULL,
    ordinal integer NOT NULL CHECK (ordinal BETWEEN 1 AND 46),
    implementation_sha256 char(64) NOT NULL,
    policy_sha256 char(64) NOT NULL,
    semantic_parameters jsonb NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (release_id, stage_id),
    CONSTRAINT uq_engine_release_stage_ordinal UNIQUE (release_id, ordinal)
);

CREATE TABLE attempts (
    id uuid PRIMARY KEY,
    subject_id uuid NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT,
    engine_release_id uuid REFERENCES engine_releases(id) ON DELETE RESTRICT,
    parent_attempt_id uuid REFERENCES attempts(id) ON DELETE RESTRICT,
    kind varchar(40) NOT NULL CHECK (kind IN ('research','repair','compile_candidate')),
    spec_sha256 char(64) NOT NULL,
    created_by varchar(300) NOT NULL,
    final_state varchar(50) NOT NULL DEFAULT 'OPEN',
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_attempts_subject_release_created
    ON attempts(subject_id, engine_release_id, created_at);

CREATE TABLE attempt_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id uuid NOT NULL REFERENCES attempts(id) ON DELETE RESTRICT,
    event_type varchar(100) NOT NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_attempt_events_attempt_created ON attempt_events(attempt_id, created_at, id);

CREATE TABLE attempt_artifacts (
    attempt_id uuid NOT NULL REFERENCES attempts(id) ON DELETE RESTRICT,
    role varchar(150) NOT NULL,
    artifact_id uuid NOT NULL REFERENCES artifacts(id) ON DELETE RESTRICT,
    origin varchar(20) NOT NULL CHECK (origin IN ('inherited','produced')),
    PRIMARY KEY (attempt_id, role)
);

CREATE TABLE compiler_run_bindings (
    attempt_id uuid PRIMARY KEY REFERENCES attempts(id) ON DELETE RESTRICT,
    compiler_run_id varchar(300) NOT NULL UNIQUE,
    run_manifest_path text NOT NULL,
    run_ledger_path text NOT NULL,
    pipeline_plan_sha256 char(64) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE executions (
    id uuid PRIMARY KEY,
    attempt_id uuid REFERENCES attempts(id) ON DELETE RESTRICT,
    workflow_id varchar(300) NOT NULL,
    workflow_run_id varchar(300),
    stage_contract varchar(200) NOT NULL,
    status varchar(40) NOT NULL,
    worker_identity varchar(300),
    retry_number integer NOT NULL DEFAULT 0 CHECK (retry_number >= 0),
    started_at timestamptz,
    finished_at timestamptz,
    error_code varchar(200),
    error_payload jsonb,
    CONSTRAINT uq_execution_retry UNIQUE (workflow_id, stage_contract, retry_number)
);
CREATE INDEX ix_executions_attempt_stage ON executions(attempt_id, stage_contract, started_at);

CREATE TABLE execution_artifacts (
    execution_id uuid NOT NULL REFERENCES executions(id) ON DELETE RESTRICT,
    relation varchar(20) NOT NULL CHECK (relation IN ('input','output')),
    role varchar(150) NOT NULL,
    artifact_id uuid NOT NULL REFERENCES artifacts(id) ON DELETE RESTRICT,
    PRIMARY KEY (execution_id, relation, role, artifact_id)
);

CREATE TABLE failure_signatures (
    id uuid PRIMARY KEY,
    attempt_id uuid NOT NULL REFERENCES attempts(id) ON DELETE RESTRICT,
    execution_id uuid REFERENCES executions(id) ON DELETE RESTRICT,
    stage_id varchar(100) NOT NULL,
    code varchar(200) NOT NULL,
    severity varchar(20) NOT NULL,
    signature_sha256 char(64) NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_attempt_failure_signature UNIQUE (attempt_id, signature_sha256)
);
CREATE INDEX ix_failure_signatures_attempt_stage ON failure_signatures(attempt_id, stage_id, created_at);

CREATE TABLE owner_attributions (
    id uuid PRIMARY KEY,
    failure_signature_id uuid NOT NULL REFERENCES failure_signatures(id) ON DELETE RESTRICT,
    owner_stage_id varchar(100) NOT NULL,
    owner_kind varchar(30) NOT NULL,
    reason text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE repair_directives (
    id uuid PRIMARY KEY,
    failure_signature_id uuid NOT NULL REFERENCES failure_signatures(id) ON DELETE RESTRICT,
    owner_stage_id varchar(100) NOT NULL,
    directive_type varchar(50) NOT NULL,
    invalidated_stage_ids jsonb NOT NULL,
    payload jsonb NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','APPLIED','SUPERSEDED')),
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_repair_directives_open_owner ON repair_directives(owner_stage_id, created_at)
    WHERE status = 'OPEN';

CREATE TABLE proofs (
    id uuid PRIMARY KEY,
    proof_type varchar(200) NOT NULL,
    subject_artifact_id uuid REFERENCES artifacts(id) ON DELETE RESTRICT,
    policy_sha256 char(64) NOT NULL,
    implementation_sha256 char(64) NOT NULL,
    result varchar(20) NOT NULL CHECK (result IN ('PASS','FAIL','ABSTAIN')),
    report_artifact_id uuid REFERENCES artifacts(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE qualifications (
    id uuid PRIMARY KEY,
    artifact_id uuid NOT NULL REFERENCES artifacts(id) ON DELETE RESTRICT,
    qualification_type varchar(200) NOT NULL,
    result varchar(20) NOT NULL CHECK (result IN ('PASS','FAIL','ABSTAIN')),
    proof_id uuid REFERENCES proofs(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_artifact_qualification_proof
    ON qualifications(artifact_id, qualification_type, proof_id)
    NULLS NOT DISTINCT;
CREATE INDEX ix_qualifications_reuse_lookup
    ON qualifications(artifact_id, qualification_type, result);

CREATE TABLE product_revisions (
    id uuid PRIMARY KEY,
    subject_id uuid NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT,
    revision_number bigint NOT NULL CHECK (revision_number > 0),
    manifest_sha256 char(64) NOT NULL,
    created_from_attempt_id uuid NOT NULL REFERENCES attempts(id) ON DELETE RESTRICT,
    sealed_at timestamptz NOT NULL,
    CONSTRAINT uq_product_revision_number UNIQUE (subject_id, revision_number),
    CONSTRAINT uq_product_revision_manifest UNIQUE (subject_id, manifest_sha256)
);

CREATE TABLE product_revision_artifacts (
    product_revision_id uuid NOT NULL REFERENCES product_revisions(id) ON DELETE RESTRICT,
    role varchar(150) NOT NULL,
    artifact_id uuid NOT NULL REFERENCES artifacts(id) ON DELETE RESTRICT,
    PRIMARY KEY (product_revision_id, role)
);

CREATE TABLE promotions (
    id uuid PRIMARY KEY,
    subject_id uuid NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT,
    from_revision_id uuid REFERENCES product_revisions(id) ON DELETE RESTRICT,
    to_revision_id uuid NOT NULL REFERENCES product_revisions(id) ON DELETE RESTRICT,
    reason text NOT NULL,
    requested_by varchar(300) NOT NULL,
    qualification_snapshot jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_promotions_subject_created ON promotions(subject_id, created_at);

CREATE TABLE subject_current_revision (
    subject_id uuid PRIMARY KEY REFERENCES subjects(id) ON DELETE RESTRICT,
    product_revision_id uuid NOT NULL REFERENCES product_revisions(id) ON DELETE RESTRICT,
    lock_version bigint NOT NULL DEFAULT 0 CHECK (lock_version >= 0),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE render_requests (
    id uuid PRIMARY KEY,
    subject_id uuid NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT,
    product_revision_id uuid NOT NULL REFERENCES product_revisions(id) ON DELETE RESTRICT,
    motion_artifact_id uuid NOT NULL REFERENCES artifacts(id) ON DELETE RESTRICT,
    view_spec jsonb NOT NULL,
    render_settings jsonb NOT NULL,
    semantic_sha256 char(64) NOT NULL UNIQUE,
    idempotency_key varchar(200) NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE render_outputs (
    render_request_id uuid NOT NULL REFERENCES render_requests(id) ON DELETE RESTRICT,
    artifact_id uuid NOT NULL REFERENCES artifacts(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (render_request_id, artifact_id)
);

CREATE TABLE commands (
    id uuid PRIMARY KEY,
    command_type varchar(100) NOT NULL,
    subject_id uuid REFERENCES subjects(id) ON DELETE RESTRICT,
    idempotency_key varchar(200) NOT NULL UNIQUE,
    payload jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE outbox_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type varchar(100) NOT NULL,
    aggregate_id uuid NOT NULL,
    event_type varchar(100) NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    delivered_at timestamptz,
    delivery_attempts integer NOT NULL DEFAULT 0 CHECK (delivery_attempts >= 0),
    claim_token uuid,
    claimed_at timestamptz,
    available_at timestamptz NOT NULL DEFAULT now(),
    last_error text
);
CREATE INDEX ix_outbox_delivery_scan
    ON outbox_events(delivered_at, available_at, claimed_at, id);

CREATE TABLE audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor varchar(300) NOT NULL,
    action varchar(150) NOT NULL,
    subject_id uuid,
    attempt_id uuid,
    product_revision_id uuid,
    artifact_id uuid,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_audit_events_subject_created ON audit_events(subject_id, created_at);
CREATE INDEX ix_audit_events_attempt_created ON audit_events(attempt_id, created_at);

-- +goose Down

DROP TABLE audit_events;
DROP TABLE outbox_events;
DROP TABLE commands;
DROP TABLE render_outputs;
DROP TABLE render_requests;
DROP TABLE subject_current_revision;
DROP TABLE promotions;
DROP TABLE product_revision_artifacts;
DROP TABLE product_revisions;
DROP TABLE qualifications;
DROP TABLE proofs;
DROP TABLE repair_directives;
DROP TABLE owner_attributions;
DROP TABLE failure_signatures;
DROP TABLE execution_artifacts;
DROP TABLE executions;
DROP TABLE compiler_run_bindings;
DROP TABLE attempt_artifacts;
DROP TABLE attempt_events;
DROP TABLE attempts;
DROP TABLE engine_release_stages;
DROP TABLE engine_releases;
DROP TABLE artifact_inputs;
DROP TABLE artifacts;
DROP TABLE artifact_types;
DROP TABLE subjects;
