#include "runtime_v3_reference.h"
#include "reference_raster_v3.h"

#include <archive.h>
#include <archive_entry.h>
#include <png.h>
#include <zlib.h>

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <limits>
#include <memory>
#include <stdexcept>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

namespace realsas::runtime_v3 {
namespace {
using reference_raster_v3::Barycentric;
using reference_raster_v3::DepthSample;
using reference_raster_v3::DepthWritePolicy;
using reference_raster_v3::Vertex;

constexpr uint32_t kVersion = 3u;
constexpr uint8_t kMagic[8] = {'R','S','R','T',0,3,0,0};
constexpr uint32_t kFeatureBakedXyz = 1u << 1;
constexpr uint32_t kFeatureDepthRenderer = 1u << 4;
constexpr uint32_t kFeaturePosedDepth = 1u << 5;
constexpr uint32_t kFeatureFullSurface = 1u << 6;
constexpr uint32_t kFeatureSlots = 1u << 7;
constexpr uint32_t kFeaturePerFaceAppearance = 1u << 10;
constexpr uint32_t kRequiredFeatures = kFeatureBakedXyz | kFeatureDepthRenderer |
    kFeaturePosedDepth | kFeatureFullSurface | kFeatureSlots | kFeaturePerFaceAppearance;

struct Vec2 { float x=0, y=0; };
struct Vec3 { float x=0, y=0, z=0; };
struct RestVertex { Vec3 rest; Vec2 uv; };
enum class AttachmentKind:uint8_t { DeformableBody=0, RigidComponent=1, Clipping=2 };
enum class TopologyClass:uint8_t { Static=0, AttachmentDynamic=1, ClipDynamic=2, DrawOrderDynamic=3 };
enum class AppearanceProvenance:uint8_t { DirectSource=0, OtherViewSource=1, UnderRigidSource=2, Unseen=3, Completion=4 };
struct Slot { std::string id,bone_id; uint32_t setup_order=0; std::string default_attachment_id; };
struct Face { std::array<uint32_t,3> tri{}; AppearanceProvenance provenance=AppearanceProvenance::Unseen; };
struct Mesh { std::string id; uint32_t slot_index=0; std::string attachment_id; AttachmentKind attachment_kind=AttachmentKind::DeformableBody; TopologyClass topology_class=TopologyClass::Static; std::vector<RestVertex> vertices; std::vector<Face> faces; };
struct View { std::string id, texture_path; uint32_t texture_crc32=0,width=0,height=0; std::vector<uint8_t> texture_rgba; std::vector<Mesh> meshes; };
struct ClipInterval { std::string clip_attachment_id; uint32_t start_slot_index=0,end_slot_index=0; bool inverse=false; };
struct FrameView { std::vector<std::vector<Vec3>> mesh_vertices; std::vector<uint32_t> draw_order_slots; std::vector<std::string> active_attachment_by_slot; std::vector<ClipInterval> clip_intervals; };
struct Frame { float time=0; std::vector<FrameView> views; };
struct Clip { std::string id,display_name,intent; float duration=0,fps=30; bool loop=false,qualified=false; std::vector<Frame> frames; };
struct RuntimeData { std::string binary_schema,source_binding_sha256,source_proof_bundle_hash,coordinate_system,playback_contract_hash,reference_raster_contract_hash; float units_per_pixel=1,alpha_cutout_threshold=.5f; uint32_t feature_flags=0; std::vector<Slot> slots; std::vector<View> views; std::vector<Clip> clips; };
struct ActiveClipMask { uint32_t start_order=0,end_order=0; bool inverse=false; std::vector<uint8_t> mask; };

class Reader {
public:
 explicit Reader(const std::vector<uint8_t>& b):b_(b){}
 void require(size_t n) const { if(off_>b_.size()||n>b_.size()-off_) throw std::runtime_error("Truncated RealSaS runtime-v3 binary"); }
 uint8_t u8(){require(1);return b_[off_++];}
 uint32_t u32(){require(4);uint32_t v=uint32_t(b_[off_])|(uint32_t(b_[off_+1])<<8)|(uint32_t(b_[off_+2])<<16)|(uint32_t(b_[off_+3])<<24);off_+=4;return v;}
 float f32(){uint32_t bits=u32();float v;std::memcpy(&v,&bits,4);if(!std::isfinite(v))throw std::runtime_error("Non-finite runtime-v3 float");return v;}
 std::string str(){uint32_t n=u32();if(n>16u*1024u*1024u)throw std::runtime_error("Unreasonable runtime-v3 string");require(n);std::string s(reinterpret_cast<const char*>(b_.data()+off_),n);off_+=n;return s;}
 void magic(){require(8);if(std::memcmp(b_.data()+off_,kMagic,8)!=0)throw std::runtime_error("Invalid runtime-v3 magic");off_+=8;}
 size_t offset()const{return off_;}
private: const std::vector<uint8_t>& b_; size_t off_=0;
};

uint32_t crc_bytes(const uint8_t* data,size_t size){uLong c=crc32(0L,Z_NULL,0);size_t o=0;while(o<size){uInt n=static_cast<uInt>(std::min<size_t>(size-o,std::numeric_limits<uInt>::max()));c=crc32(c,data+o,n);o+=n;}return uint32_t(c);}
std::vector<uint8_t> read_file(const std::filesystem::path&p){std::ifstream f(p,std::ios::binary);if(!f)throw std::runtime_error("Cannot open file: "+p.string());f.seekg(0,std::ios::end);auto n=f.tellg();if(n<0)throw std::runtime_error("Cannot size file");f.seekg(0);std::vector<uint8_t> b(static_cast<size_t>(n),uint8_t{0});if(!b.empty())f.read(reinterpret_cast<char*>(b.data()),std::streamsize(b.size()));if(!f&&!b.empty())throw std::runtime_error("Cannot read file");return b;}
std::vector<uint8_t> archive_entry_bytes(const std::filesystem::path&p,std::string_view wanted){archive* a=archive_read_new();if(!a)throw std::runtime_error("libarchive allocation failed");std::unique_ptr<archive,decltype(&archive_read_free)> hold(a,&archive_read_free);archive_read_support_filter_all(a);archive_read_support_format_all(a);if(archive_read_open_filename(a,p.string().c_str(),10240)!=ARCHIVE_OK)throw std::runtime_error(std::string("Cannot open archive: ")+archive_error_string(a));archive_entry* e=nullptr;while(archive_read_next_header(a,&e)==ARCHIVE_OK){const char* name=archive_entry_pathname(e);if(name&&wanted==name){la_int64_t dn=archive_entry_size(e);if(dn<0||dn>la_int64_t(3ull<<30))throw std::runtime_error("Invalid archive entry size");std::vector<uint8_t> out(static_cast<size_t>(dn),uint8_t{0});size_t o=0;while(o<out.size()){la_ssize_t g=archive_read_data(a,out.data()+o,out.size()-o);if(g<0)throw std::runtime_error(std::string("Archive read failed: ")+archive_error_string(a));if(g==0)break;o+=size_t(g);}if(o!=out.size())throw std::runtime_error("Truncated archive entry");return out;}archive_read_data_skip(a);}throw std::runtime_error("Archive entry not found: "+std::string(wanted));}
std::vector<uint8_t> package_asset(const std::filesystem::path&p,std::string_view rel){if(std::filesystem::is_directory(p)){auto root=std::filesystem::weakly_canonical(p);auto c=std::filesystem::weakly_canonical(root/std::filesystem::path(rel));auto ri=root.begin(),ci=c.begin();for(;ri!=root.end()&&ci!=c.end();++ri,++ci)if(*ri!=*ci)throw std::runtime_error("Runtime-v3 path escape");if(ri!=root.end())throw std::runtime_error("Runtime-v3 path escape");return read_file(c);}return archive_entry_bytes(p,rel);}
std::vector<uint8_t> decode_png(const std::vector<uint8_t>& b,uint32_t w,uint32_t h){png_image im{};im.version=PNG_IMAGE_VERSION;if(!png_image_begin_read_from_memory(&im,b.data(),b.size()))throw std::runtime_error("PNG header decode failed");im.format=PNG_FORMAT_RGBA;if(im.width!=w||im.height!=h){png_image_free(&im);throw std::runtime_error("Texture dimensions disagree with binary");}std::vector<uint8_t> out(PNG_IMAGE_SIZE(im));if(!png_image_finish_read(&im,nullptr,out.data(),0,nullptr)){std::string m=im.message;png_image_free(&im);throw std::runtime_error("PNG decode failed: "+m);}png_image_free(&im);return out;}
AttachmentKind parse_kind(uint8_t v){if(v>2)throw std::runtime_error("Invalid attachment kind");return AttachmentKind(v);} TopologyClass parse_topo(uint8_t v){if(v>3)throw std::runtime_error("Invalid topology class");return TopologyClass(v);} AppearanceProvenance parse_prov(uint8_t v){if(v>4)throw std::runtime_error("Invalid appearance provenance");return AppearanceProvenance(v);}
void exact_permutation(const std::vector<uint32_t>& o,size_t n){if(o.size()!=n)throw std::runtime_error("Draw order is not exact slot permutation");std::vector<bool>s(n,false);for(uint32_t x:o){if(x>=n||s[x])throw std::runtime_error("Draw order is not exact slot permutation");s[x]=true;}}

RuntimeData parse_binary(const std::vector<uint8_t>& bytes){
    if(bytes.size()<16)throw std::runtime_error("Runtime-v3 binary too small");
    const size_t body_n=bytes.size()-4;
    const uint32_t stored=uint32_t(bytes[body_n])|(uint32_t(bytes[body_n+1])<<8)|(uint32_t(bytes[body_n+2])<<16)|(uint32_t(bytes[body_n+3])<<24);
    if(stored!=crc_bytes(bytes.data(),body_n))throw std::runtime_error("Runtime-v3 CRC32 mismatch");
    std::vector<uint8_t> body(bytes.begin(),bytes.begin()+std::ptrdiff_t(body_n));
    Reader r(body);r.magic();if(r.u32()!=kVersion)throw std::runtime_error("Unsupported runtime-v3 version");
    RuntimeData d;d.binary_schema=r.str();d.source_binding_sha256=r.str();d.source_proof_bundle_hash=r.str();d.coordinate_system=r.str();d.units_per_pixel=r.f32();d.feature_flags=r.u32();d.playback_contract_hash=r.str();d.reference_raster_contract_hash=r.str();d.alpha_cutout_threshold=r.f32();
    if(d.binary_schema!="RealSaS.RuntimeBinary.rsr.v3")throw std::runtime_error("Unexpected runtime-v3 schema");
    if(d.source_binding_sha256.size()!=64||d.source_proof_bundle_hash.size()!=64||d.playback_contract_hash.size()!=64||d.reference_raster_contract_hash.size()!=64)throw std::runtime_error("Runtime-v3 identity is not SHA-256 length");
    if(d.coordinate_system!="screen_2d.top_left.x_right.y_down.depth_camera_forward")throw std::runtime_error("Runtime-v3 coordinate mismatch");
    if(!(d.units_per_pixel>0))throw std::runtime_error("Invalid unit scale");
    if((d.feature_flags&kRequiredFeatures)!=kRequiredFeatures)throw std::runtime_error("Runtime-v3 lacks required depth/appearance capabilities");
    if(d.alpha_cutout_threshold<0||d.alpha_cutout_threshold>1)throw std::runtime_error("Invalid cutout threshold");

    uint32_t ns=r.u32();if(ns==0||ns>4096)throw std::runtime_error("Invalid slot count");d.slots.reserve(ns);std::unordered_set<std::string> slot_ids;std::unordered_set<uint32_t> orders;for(uint32_t i=0;i<ns;++i){Slot s;s.id=r.str();s.bone_id=r.str();s.setup_order=r.u32();s.default_attachment_id=r.str();if(s.id.empty()||!slot_ids.insert(s.id).second)throw std::runtime_error("Duplicate/empty slot id");if(!orders.insert(s.setup_order).second)throw std::runtime_error("Slot setup order must be total");d.slots.push_back(std::move(s));}
    uint32_t nv=r.u32();if(nv==0||nv>64)throw std::runtime_error("Invalid view count");d.views.reserve(nv);std::unordered_set<std::string> view_ids,mesh_ids;std::unordered_map<std::string,std::pair<uint32_t,AttachmentKind>> semantics;
    for(uint32_t vi=0;vi<nv;++vi){View v;v.id=r.str();v.texture_path=r.str();v.texture_crc32=r.u32();v.width=r.u32();v.height=r.u32();if(v.id.empty()||!view_ids.insert(v.id).second)throw std::runtime_error("Duplicate/empty view id");if(v.texture_path.empty()||v.width==0||v.height==0||v.width>32768||v.height>32768)throw std::runtime_error("Invalid view texture metadata");uint32_t nm=r.u32();if(nm==0||nm>4096)throw std::runtime_error("Invalid mesh count");v.meshes.reserve(nm);std::unordered_set<std::string> local_attachments;for(uint32_t mi=0;mi<nm;++mi){Mesh m;m.id=r.str();m.slot_index=r.u32();m.attachment_id=r.str();m.attachment_kind=parse_kind(r.u8());m.topology_class=parse_topo(r.u8());(void)r.u8();(void)r.u8();uint32_t nvert=r.u32(),nface=r.u32();if(m.id.empty()||!mesh_ids.insert(m.id).second)throw std::runtime_error("Duplicate/empty mesh id");if(m.slot_index>=d.slots.size())throw std::runtime_error("Mesh slot out of range");if(m.attachment_id.empty()||!local_attachments.insert(m.attachment_id).second)throw std::runtime_error("Duplicate/empty attachment variant");auto sem=std::make_pair(m.slot_index,m.attachment_kind);auto it=semantics.find(m.attachment_id);if(it==semantics.end())semantics.emplace(m.attachment_id,sem);else if(it->second!=sem)throw std::runtime_error("Attachment semantic drift across views");if(nvert==0||nvert>10000000u||nface==0||nface>20000000u)throw std::runtime_error("Invalid mesh dimensions");m.vertices.resize(nvert);for(auto&rv:m.vertices){rv.rest={r.f32(),r.f32(),r.f32()};rv.uv={r.f32(),r.f32()};if(rv.uv.x<0||rv.uv.x>1||rv.uv.y<0||rv.uv.y>1)throw std::runtime_error("UV outside [0,1]");}m.faces.resize(nface);for(auto&f:m.faces){f.tri={r.u32(),r.u32(),r.u32()};if(f.tri[0]>=nvert||f.tri[1]>=nvert||f.tri[2]>=nvert)throw std::runtime_error("Triangle index out of range");f.provenance=parse_prov(r.u8());(void)r.u8();(void)r.u8();(void)r.u8();}v.meshes.push_back(std::move(m));}d.views.push_back(std::move(v));}
    for(const auto&s:d.slots)if(!s.default_attachment_id.empty()){auto it=semantics.find(s.default_attachment_id);if(it==semantics.end()||it->second.first>=d.slots.size())throw std::runtime_error("Invalid default attachment");}
    uint32_t nc=r.u32();if(nc==0||nc>4096)throw std::runtime_error("Invalid clip count");d.clips.reserve(nc);std::unordered_set<std::string> clip_ids;
    for(uint32_t ci=0;ci<nc;++ci){Clip c;c.id=r.str();c.display_name=r.str();c.intent=r.str();c.duration=r.f32();c.fps=r.f32();c.loop=r.u8()!=0;c.qualified=r.u8()!=0;(void)r.u8();(void)r.u8();uint32_t nf=r.u32();if(c.id.empty()||!clip_ids.insert(c.id).second||!(c.duration>0)||!(c.fps>0)||nf==0||nf>1000000u)throw std::runtime_error("Invalid clip metadata");c.frames.reserve(nf);float prior=-1;for(uint32_t fi=0;fi<nf;++fi){Frame fr;fr.time=r.f32();if(fr.time<prior)throw std::runtime_error("Frame times unordered");prior=fr.time;fr.views.resize(d.views.size());for(size_t vi=0;vi<d.views.size();++vi){const View&v=d.views[vi];FrameView&fv=fr.views[vi];fv.mesh_vertices.resize(v.meshes.size());for(size_t mi=0;mi<v.meshes.size();++mi){auto&pts=fv.mesh_vertices[mi];pts.resize(v.meshes[mi].vertices.size());for(auto&p:pts)p={r.f32(),r.f32(),r.f32()};}uint32_t nd=r.u32();fv.draw_order_slots.resize(nd);for(auto&x:fv.draw_order_slots)x=r.u32();exact_permutation(fv.draw_order_slots,d.slots.size());uint32_t na=r.u32();if(na!=d.slots.size())throw std::runtime_error("Active attachment map incomplete");fv.active_attachment_by_slot.resize(na);for(auto&a:fv.active_attachment_by_slot)a=r.str();uint32_t ni=r.u32();if(ni>d.slots.size())throw std::runtime_error("Invalid clip interval count");fv.clip_intervals.resize(ni);std::vector<uint32_t> pos(d.slots.size());for(uint32_t oi=0;oi<fv.draw_order_slots.size();++oi)pos[fv.draw_order_slots[oi]]=oi;std::unordered_set<std::string> interval_ids;for(auto&in:fv.clip_intervals){in.clip_attachment_id=r.str();in.start_slot_index=r.u32();in.end_slot_index=r.u32();in.inverse=r.u8()!=0;(void)r.u8();(void)r.u8();(void)r.u8();if(in.clip_attachment_id.empty()||in.start_slot_index>=d.slots.size()||in.end_slot_index>=d.slots.size())throw std::runtime_error("Invalid clip interval");if(!(pos[in.start_slot_index]<pos[in.end_slot_index]))throw std::runtime_error("Clip interval must target subsequent slot range");if(!interval_ids.insert(in.clip_attachment_id).second)throw std::runtime_error("Duplicate clip interval");if(fv.active_attachment_by_slot[in.start_slot_index]!=in.clip_attachment_id)throw std::runtime_error("Clip interval start slot/attachment mismatch");}for(uint32_t si=0;si<fv.active_attachment_by_slot.size();++si){const std::string&a=fv.active_attachment_by_slot[si];if(a.empty())continue;auto sit=semantics.find(a);if(sit==semantics.end()||sit->second.first!=si)throw std::runtime_error("Active attachment slot mismatch");if(sit->second.second==AttachmentKind::Clipping&&!interval_ids.count(a))throw std::runtime_error("Active clipping attachment missing interval");}}c.frames.push_back(std::move(fr));}d.clips.push_back(std::move(c));}
    if(r.offset()!=body.size())throw std::runtime_error("Trailing bytes in runtime-v3 binary");
    return d;
}

float norm_time(const Clip&c,float t){if(!std::isfinite(t))t=0;t=std::max(0.0f,t);if(c.duration>0){if(c.loop){t=std::fmod(t,c.duration);if(t<0)t+=c.duration;}else t=std::min(t,c.duration);}return t;}
struct Span{const Frame*a=nullptr;const Frame*b=nullptr;float alpha=0;};
Span sample_span(const Clip&c,float t){if(c.frames.empty())throw std::runtime_error("Clip has no frames");t=norm_time(c,t);auto up=std::lower_bound(c.frames.begin(),c.frames.end(),t,[](const Frame&f,float v){return f.time<v;});if(up==c.frames.begin())return{&c.frames.front(),&c.frames.front(),0};if(up==c.frames.end())return{&c.frames.back(),&c.frames.back(),0};const Frame*b=&*up;const Frame*a=&*(up-1);float den=b->time-a->time;return{a,b,den>1e-8f?std::clamp((t-a->time)/den,0.0f,1.0f):0.0f};}
Vec3 lerp(Vec3 a,Vec3 b,float t){return{a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t,a.z+(b.z-a.z)*t};}
std::array<float,4> texel(const View&v,float u,float vv){u=std::clamp(u,0.0f,1.0f);vv=std::clamp(vv,0.0f,1.0f);float x=u*float(std::max(1u,v.width-1)),y=vv*float(std::max(1u,v.height-1));uint32_t x0=uint32_t(std::floor(x)),y0=uint32_t(std::floor(y)),x1=std::min(v.width-1,x0+1),y1=std::min(v.height-1,y0+1);float tx=x-x0,ty=y-y0;auto p=[&](uint32_t xx,uint32_t yy){size_t i=(size_t(yy)*v.width+xx)*4;return std::array<float,4>{v.texture_rgba[i]/255.0f,v.texture_rgba[i+1]/255.0f,v.texture_rgba[i+2]/255.0f,v.texture_rgba[i+3]/255.0f};};auto a=p(x0,y0),b=p(x1,y0),c=p(x0,y1),d=p(x1,y1);std::array<float,4>o{};for(int k=0;k<4;++k){float q=a[k]+(b[k]-a[k])*tx,r=c[k]+(d[k]-c[k])*tx;o[k]=q+(r-q)*ty;}return o;}
void blend(uint8_t*dst,const std::array<float,4>&s){float sa=std::clamp(s[3],0.0f,1.0f);if(sa<=0)return;float da=dst[3]/255.0f,oa=sa+da*(1-sa);if(oa<=1e-8f){std::memset(dst,0,4);return;}for(int c=0;c<3;++c){float dc=dst[c]/255.0f,oc=(s[c]*sa+dc*da*(1-sa))/oa;dst[c]=uint8_t(std::clamp(std::lround(oc*255.0f),0l,255l));}dst[3]=uint8_t(std::clamp(std::lround(oa*255.0f),0l,255l));}
const Mesh& active_mesh(const View&v,uint32_t slot,const std::string&a,size_t*out){const Mesh*f=nullptr;size_t idx=0;for(size_t i=0;i<v.meshes.size();++i){const auto&m=v.meshes[i];if(m.slot_index==slot&&m.attachment_id==a){if(f)throw std::runtime_error("Active attachment resolves to multiple meshes");f=&m;idx=i;}}if(!f)throw std::runtime_error("Active attachment variant missing in view");if(out)*out=idx;return *f;}
DepthWritePolicy depth_policy(AttachmentKind k){if(k==AttachmentKind::DeformableBody)return DepthWritePolicy::On;if(k==AttachmentKind::RigidComponent)return DepthWritePolicy::CutoutOnly;throw std::runtime_error("Clipping attachment reached color renderer");}
void triangle_bounds(const View&v,const Vertex&a,const Vertex&b,const Vertex&c,int&minx,int&maxx,int&miny,int&maxy){float lx=std::min({a.x,b.x,c.x}),hx=std::max({a.x,b.x,c.x}),ly=std::min({a.y,b.y,c.y}),hy=std::max({a.y,b.y,c.y});minx=std::max(0,int(std::floor(lx-.5f)));maxx=std::min(int(v.width)-1,int(std::ceil(hx-.5f)));miny=std::max(0,int(std::floor(ly-.5f)));maxy=std::min(int(v.height)-1,int(std::ceil(hy-.5f)));}
std::vector<uint8_t> build_mask(const View&v,const Mesh&m,const std::vector<Vec3>&pa,const std::vector<Vec3>&pb,float alpha,bool inverse){size_t n=size_t(v.width)*v.height;std::vector<uint8_t> mask(n,inverse?1:0);for(const Face&f:m.faces){auto t=f.tri;Vec3 p0=lerp(pa[t[0]],pb[t[0]],alpha),p1=lerp(pa[t[1]],pb[t[1]],alpha),p2=lerp(pa[t[2]],pb[t[2]],alpha);Vertex a{p0.x,p0.y,p0.z,0,0},b{p1.x,p1.y,p1.z,0,0},c{p2.x,p2.y,p2.z,0,0};int minx,maxx,miny,maxy;triangle_bounds(v,a,b,c,minx,maxx,miny,maxy);for(int y=miny;y<=maxy;++y)for(int x=minx;x<=maxx;++x){auto bc=reference_raster_v3::cover_pixel_center(a,b,c,x,y);if(!bc.covered)continue;mask[size_t(y)*v.width+x]=inverse?0:1;}}return mask;}
bool mask_allows(const std::vector<ActiveClipMask>&masks,uint32_t order,size_t pix){for(const auto&m:masks)if(order>m.start_order&&order<=m.end_order&&!m.mask[pix])return false;return true;}
void render_face(const View&v,const Mesh&m,const std::vector<Vec3>&pa,const std::vector<Vec3>&pb,float alpha,const Face&f,uint32_t order,float cut,const std::vector<ActiveClipMask>&masks,std::vector<DepthSample>&depth,std::vector<uint8_t>&rgba){if(f.provenance==AppearanceProvenance::Unseen)return;auto t=f.tri;Vec3 p0=lerp(pa[t[0]],pb[t[0]],alpha),p1=lerp(pa[t[1]],pb[t[1]],alpha),p2=lerp(pa[t[2]],pb[t[2]],alpha);auto&r0=m.vertices[t[0]],&r1=m.vertices[t[1]],&r2=m.vertices[t[2]];Vertex a{p0.x,p0.y,p0.z,r0.uv.x,r0.uv.y},b{p1.x,p1.y,p1.z,r1.uv.x,r1.uv.y},c{p2.x,p2.y,p2.z,r2.uv.x,r2.uv.y};int minx,maxx,miny,maxy;triangle_bounds(v,a,b,c,minx,maxx,miny,maxy);auto policy=depth_policy(m.attachment_kind);for(int y=miny;y<=maxy;++y)for(int x=minx;x<=maxx;++x){auto bc=reference_raster_v3::cover_pixel_center(a,b,c,x,y);if(!bc.covered)continue;size_t pix=size_t(y)*v.width+x;if(!mask_allows(masks,order,pix))continue;float z=reference_raster_v3::interpolate_depth(bc,a,b,c);if(!reference_raster_v3::depth_test_passes(depth[pix],z,order))continue;float u=a.u*bc.w0+b.u*bc.w1+c.u*bc.w2,vv=a.v*bc.w0+b.v*bc.w1+c.v*bc.w2;auto s=texel(v,u,vv);float aa=std::clamp(s[3],0.0f,1.0f);if(aa<=0)continue;blend(rgba.data()+pix*4,s);if(reference_raster_v3::should_write_depth(policy,aa,cut))reference_raster_v3::commit_depth(depth[pix],z,order);}}
std::vector<uint8_t> render_frame(const RuntimeData&d,uint32_t ci,uint32_t vi,float time){if(ci>=d.clips.size()||vi>=d.views.size())throw std::out_of_range("clip/view index out of range");const Clip&c=d.clips[ci];const View&v=d.views[vi];Span sp=sample_span(c,time);const FrameView&a=sp.a->views[vi],&b=sp.b->views[vi];const FrameView&comp=sp.alpha<.5f?a:b;if(comp.active_attachment_by_slot.size()!=d.slots.size())throw std::runtime_error("Sampled active attachment map incomplete");size_t pixels=size_t(v.width)*v.height;std::vector<uint8_t> rgba(pixels*4,0);std::vector<DepthSample> depth(pixels);std::vector<uint32_t> pos(d.slots.size());for(uint32_t oi=0;oi<comp.draw_order_slots.size();++oi)pos[comp.draw_order_slots[oi]]=oi;std::unordered_map<std::string,const ClipInterval*> interval_by_id;for(const auto&in:comp.clip_intervals)interval_by_id[in.clip_attachment_id]=&in;std::vector<ActiveClipMask> masks;for(uint32_t rank=0;rank<comp.draw_order_slots.size();++rank){uint32_t slot=comp.draw_order_slots[rank];const std::string&aid=comp.active_attachment_by_slot[slot];if(aid.empty())continue;size_t mi=0;const Mesh&m=active_mesh(v,slot,aid,&mi);if(mi>=a.mesh_vertices.size()||mi>=b.mesh_vertices.size())throw std::runtime_error("Frame/mesh topology drift");const auto&pa=a.mesh_vertices[mi],&pb=b.mesh_vertices[mi];if(pa.size()!=m.vertices.size()||pb.size()!=m.vertices.size())throw std::runtime_error("Frame vertex count drift");if(m.attachment_kind==AttachmentKind::Clipping){auto it=interval_by_id.find(aid);if(it==interval_by_id.end())throw std::runtime_error("Active clipping attachment missing sampled interval");const auto&in=*it->second;if(in.start_slot_index!=slot)throw std::runtime_error("Clip start slot mismatch at render");ActiveClipMask cm;cm.start_order=pos[in.start_slot_index];cm.end_order=pos[in.end_slot_index];cm.inverse=in.inverse;cm.mask=build_mask(v,m,pa,pb,sp.alpha,in.inverse);masks.push_back(std::move(cm));continue;}for(size_t fi=0;fi<m.faces.size();++fi){uint32_t local=uint32_t(std::min<size_t>(fi,0xFFFFFu));uint32_t order=(std::min<uint32_t>(rank,0xFFFu)<<20)|local;render_face(v,m,pa,pb,sp.alpha,m.faces[fi],order,d.alpha_cutout_threshold,masks,depth,rgba);}masks.erase(std::remove_if(masks.begin(),masks.end(),[&](const ActiveClipMask&cm){return rank>=cm.end_order;}),masks.end());}return rgba;}
}

struct ReferenceRuntime::Impl { std::filesystem::path package_path; RuntimeData data; };
ReferenceRuntime::ReferenceRuntime(const std::filesystem::path&p):impl_(std::make_unique<Impl>()){impl_->package_path=std::filesystem::absolute(p);if(!std::filesystem::exists(impl_->package_path))throw std::runtime_error("Runtime-v3 package does not exist");impl_->data=parse_binary(package_asset(impl_->package_path,"runtime/realsas_runtime.rsr"));for(auto&v:impl_->data.views){auto b=package_asset(impl_->package_path,v.texture_path);if(crc_bytes(b.data(),b.size())!=v.texture_crc32)throw std::runtime_error("Texture CRC32 mismatch: "+v.id);v.texture_rgba=decode_png(b,v.width,v.height);}}
ReferenceRuntime::~ReferenceRuntime()=default;ReferenceRuntime::ReferenceRuntime(ReferenceRuntime&&) noexcept=default;ReferenceRuntime&ReferenceRuntime::operator=(ReferenceRuntime&&) noexcept=default;
const std::string&ReferenceRuntime::binary_schema()const noexcept{return impl_->data.binary_schema;}const std::string&ReferenceRuntime::source_binding_sha256()const noexcept{return impl_->data.source_binding_sha256;}const std::string&ReferenceRuntime::source_proof_bundle_hash()const noexcept{return impl_->data.source_proof_bundle_hash;}const std::string&ReferenceRuntime::coordinate_system()const noexcept{return impl_->data.coordinate_system;}const std::string&ReferenceRuntime::playback_contract_hash()const noexcept{return impl_->data.playback_contract_hash;}const std::string&ReferenceRuntime::reference_raster_contract_hash()const noexcept{return impl_->data.reference_raster_contract_hash;}float ReferenceRuntime::units_per_pixel()const noexcept{return impl_->data.units_per_pixel;}uint32_t ReferenceRuntime::feature_flags()const noexcept{return impl_->data.feature_flags;}float ReferenceRuntime::alpha_cutout_threshold()const noexcept{return impl_->data.alpha_cutout_threshold;}
uint32_t ReferenceRuntime::view_count()const noexcept{return uint32_t(impl_->data.views.size());}const std::string&ReferenceRuntime::view_id(uint32_t i)const{if(i>=impl_->data.views.size())throw std::out_of_range("view index");return impl_->data.views[i].id;}uint32_t ReferenceRuntime::view_width(uint32_t i)const{if(i>=impl_->data.views.size())throw std::out_of_range("view index");return impl_->data.views[i].width;}uint32_t ReferenceRuntime::view_height(uint32_t i)const{if(i>=impl_->data.views.size())throw std::out_of_range("view index");return impl_->data.views[i].height;}uint32_t ReferenceRuntime::find_view(const std::string&s)const noexcept{for(uint32_t i=0;i<impl_->data.views.size();++i)if(impl_->data.views[i].id==s)return i;return UINT32_MAX;}
uint32_t ReferenceRuntime::clip_count()const noexcept{return uint32_t(impl_->data.clips.size());}const std::string&ReferenceRuntime::clip_id(uint32_t i)const{if(i>=impl_->data.clips.size())throw std::out_of_range("clip index");return impl_->data.clips[i].id;}const std::string&ReferenceRuntime::clip_display_name(uint32_t i)const{if(i>=impl_->data.clips.size())throw std::out_of_range("clip index");return impl_->data.clips[i].display_name;}const std::string&ReferenceRuntime::clip_intent(uint32_t i)const{if(i>=impl_->data.clips.size())throw std::out_of_range("clip index");return impl_->data.clips[i].intent;}float ReferenceRuntime::clip_duration(uint32_t i)const{if(i>=impl_->data.clips.size())throw std::out_of_range("clip index");return impl_->data.clips[i].duration;}bool ReferenceRuntime::clip_qualified(uint32_t i)const{if(i>=impl_->data.clips.size())throw std::out_of_range("clip index");return impl_->data.clips[i].qualified;}uint32_t ReferenceRuntime::find_clip(const std::string&s)const noexcept{for(uint32_t i=0;i<impl_->data.clips.size();++i){const auto&c=impl_->data.clips[i];if(c.id==s||c.intent==s||c.display_name==s)return i;}return UINT32_MAX;}
std::vector<uint8_t> ReferenceRuntime::render_rgba(uint32_t ci,uint32_t vi,float t)const{return render_frame(impl_->data,ci,vi,t);}
}
